### ISSUE TITLE
git lfs failed

### ISSUE THREAD

**Issue by zys864** [andreabergia/rjvm#16]
Downloading vm/rt.jar (60 MB) Error downloading object: vm/rt.jar (bbdd2f5): Smudge error: Error downloading vm/rt.jar (bbdd2f5909ea77fa115f03a2b030f231cc4bf720528b0436f83459a2be429349): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by andreabergia** [comment]
Fixed by removing the file from git LFS (it's one file that has never changed after all, LFS is overkill).
