### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by andreabergia** [andreabergia/rjvm#8]
We need to support multiple threads.

**Comment by immetoo** [comment]
No please no, shared memory and thus CAS locks are design error, just like cache and threads.
After 20+ yr ERP software on java, a true single process or an zero threads jvm is missing in the options.
In current OS api with many processes with pipes to the reactor process above handles fine large loads with zero (userland) shared memory.
And single process code can be proven to work as written.
Threaded code is fizzy testing and hope for the best, but it always fails, always.
On current jdk's i still have CAS lock segfaults just like on 1.3, zero progress in 20+ years.
This OS kernel api is wrong, please don't use it.

**Comment by andreabergia** [comment]
Won't fix this.
